version: '2'

services:
  primary:
    image: docker.f4tech.com/jenkins/base-debian-jenkins:test
    ports:
      - '8095:8080'
      - '50095:50095'
    environment:
      SEED_JOBS_REPO: 'git@github.com:brandon-fryslie/10ft-ci.git'
      SEED_JOBS_BRANCH: 'bfryslie_wip'
      JENKINS_SLAVE_PORT: '50095'
      JENKINS_TYPE: primary
      JENKINS_FQDN: cici.ci.f4tech.com
      GITHUB_CLIENT_ID: c290b5641d6b1e6e57f1
      GITHUB_CLIENT_SECRET: 86429363a18e0f9a4cd59acca0f02e59c58e33d2
      JAVA_OPTS: -Xmx4G
    volumes_from:
      - data

  test:
    image: docker.f4tech.com/jenkins/base-debian-jenkins:test
    ports:
      - '8096:8080'
      - '50096:50096'
    environment:
      SEED_JOBS_REPO: 'git@github.com:brandon-fryslie/10ft-ci.git'
      SEED_JOBS_BRANCH: 'bfryslie_wip'
      JENKINS_SLAVE_PORT: '50096'
      JENKINS_TYPE: test
      JENKINS_FQDN: cici.ci.f4tech.com
      GITHUB_CLIENT_ID: c290b5641d6b1e6e57f1
      GITHUB_CLIENT_SECRET: 86429363a18e0f9a4cd59acca0f02e59c58e33d2
      JAVA_OPTS: -Xmx4G

  data:
    image: docker.f4tech.com/jenkins/jenkins-data
    environment:
      S3_BUCKET_FOLDER: cici-ci
      BACKUP_FREQUENCY: 3h
